/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pcbje_sdhashjni_SDHash_JNI */

#ifndef _Included_com_pcbje_sdhashjni_SDHash_JNI
#define _Included_com_pcbje_sdhashjni_SDHash_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pcbje_sdhashjni_SDHash_JNI
 * Method:    getSDBFFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pcbje_sdhashjni_SDHash_1JNI_getSDBFFromFile
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_pcbje_sdhashjni_SDHash_JNI
 * Method:    getSDBF
 * Signature: (Ljava/lang/String;[BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pcbje_sdhashjni_SDHash_1JNI_getSDBF
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     com_pcbje_sdhashjni_SDHash_JNI
 * Method:    compare
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pcbje_sdhashjni_SDHash_1JNI_compare___3BI
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_pcbje_sdhashjni_SDHash_JNI
 * Method:    compare
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pcbje_sdhashjni_SDHash_1JNI_compare__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
